### ISSUE TITLE
plot.PLS.resutls doesn't exist

### ISSUE THREAD

**Issue by caragreen** [dgrapov/TeachingDemos#4]
Hi,

Just quickly going through the demonstration and I'm getting this error. 

plot.PLS.results(obj=final,plot="scores",groups=group)
Error: could not find function "plot.PLS.results"

Has the function changed?

Best,

Cara

**Comment by dgrapov** [comment]
Hi,

That tutorial needs to be updated.  Specifically `plot.PLS.results` is now replaced by `plot.PLS`. It has the following arguments:

```r
plot.PLS(obj, results = c("screeplot","scores","loadings","biplot"),xaxis=1,yaxis=2,size=3,color=NULL, shape=NULL, label=TRUE, legend.name =  NULL, font.size=5,group.bounds=c("ellipse","polygon","none"),alpha=.5,g.alpha=.2,print.plot=TRUE,extra=NULL,...)
```
To replicate the plot in the tutorial the following should work:

```r
plot.PLS(obj=final, results = "scores", color=tmp.group, group.bounds="polygon", label=FALSE)
```

I'll try to update the tutorial soonish :snail:

**Comment by dgrapov** [comment]
Thanks for catching this. I just [updated that example](https://github.com/dgrapov/TeachingDemos/blob/master/Demos/Predictive%20Modeling/Iris%20O-PLS-DA/O-PLS_modeling_of_Iris_data.md#vergin_versi) and added a section comparing random forest to O-PLS

**Comment by caragreen** [comment]
Hey there,

Amazing, thanks for getting back to me so quickly, sorry I didn't reply sooner I was on a flight to Seattle! I'll try it out in the week.

All the bEst

Cara



On 7 Nov 2015, at 09:51, Dmitry Grapov <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for catching this. I just updated that example<https://github.com/dgrapov/TeachingDemos/blob/master/Demos/Predictive%20Modeling/Iris%20O-PLS-DA/O-PLS_modeling_of_Iris_data.md#vergin_versi> and added a section comparing random forest to O-PLS

-
Reply to this email directly or view it on GitHub<https://github.com/dgrapov/TeachingDemos/issues/4#issuecomment-154729953>.


The University of Aberdeen is a charity registered in Scotland, No SC013683.
Tha Oilthigh Obar Dheathain na charthannas cl?raichte ann an Alba, ?ir. SC013683.
