### ISSUE TITLE
ERROR with source code

### ISSUE THREAD

**Issue by caragreen** [dgrapov/TeachingDemos#6]
Hi there, 

I've been using your oplsda code for a while (because it is awesome!) but suddenly I am getting this error when I try and load the source code at the start. 

source("http://pastebin.com/raw.php?i=UyDBTA57")
Loading required package: RCurl
Loading required package: bitops
Error in function (type, msg, asError = TRUE)  : 
  error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

I have tried a few different things using different computers, but nothing seems to work. Do you know if it is me or if there is something wrong with the code itself? I tried manually copying and pasting your source code scripts into R, but it bugs out quite a lot. 

All the best, 

Cara

**Comment by dgrapov** [comment]
Hi,

Sorry, this code is not supported any more. I would try [ropls](https://bioconductor.org/packages/release/bioc/html/ropls.html) for opls-da instead.

**Comment by vsoch** [comment]
Can you not just clone the Repo, and use the scripts on your host?

```
git clone https://github.com/dgrapov/devium && cd devium/R
```

**Comment by vsoch** [comment]
Fantastic! Thank you @dgrapov. @caragreen does that work for you?

**Comment by dgrapov** [comment]
This is a bit dated but could work: https://zenodo.org/record/17459
